#!/bin/bash

if [ -e $1.make ]; then
    if [ $# == 3 ]; then
	cat $1.make | sed -r 's/(projects\['$2'\]\[version\]) = (.*)/\1 = "'$3'"/' > $1.make.new_temp;
	cmp -s $1.make $1.make.new_temp > /dev/null;
	if [ $? -eq 1 ]; then
	    mv $1.make $1.make.$(date +%s);
	    mv $1.make.new_temp $1.make;
	    echo "Updated $2 to version $3 for $1";
	else
	    rm $1.make.new_temp;
	    echo "$2 already update to date for $1";
	fi;
    else
	echo "Missing arguments";
    fi;
fi
